### PR TITLE
Update free area

### PR DESCRIPTION
**Pull request by d3m3vilurr**
now looks same section between LUMA

### CODE REVIEW

**Comment by nedwill** [comment]
Wow great, I was just working on getting the physical translation working and they all line up for these lower addresses.

**Comment by nedwill** [comment]
Actually we still have:
```
9.2:
[L2S] VA fff20000..fff2d000 -> PA 1ffdf000..1ffec000 [  X ] [ Priv: R-, User: -- ]
11.1:
[L2S] VA fff20000..fff2e000 -> PA 1ffde000..1ffec000 [  X ] [ Priv: R-, User: -- ]
```

**Comment by d3m3vilurr** [comment]
ok. these address are totally broken. (only compatable 11.2, i guess)
early morning, actually i haven't deep thinking about memory layout.
(just thought, probably they are linear..)

and then i rechecked these values. problem is,
current script only can check PA.
or must be more complicate for getting VA value.
other values are not impacted this problem.(all values allocatated inside 0x1ffa0000)

I guess maybe we need to search free area at runtime like LUMA.

**Comment by nedwill** [comment]
Yeah, we probably have to search these dynamically.

**Pull request merged**
