### PR TITLE
Support more n3ds versions

### PR DESCRIPTION
**Pull request by d3m3vilurr**
- Remove magic values and introduce version map table
- Add helper script for finding address

but only test n3ds 10.3 :)

### CODE REVIEW

**Comment by nedwill** [comment]
This looks fantastic! Returning tomorrow to continue work again. This will make it a lot faster. It's exactly what I had in mind for multi-version support. I'll test on my N3DS (should work), then I can do the fix that'll make it work more often.

**Comment by lotsa-spaghetti** [comment]
Is the code adaptable to o3DS?

**Comment by d3m3vilurr** [comment]
don't know yet. i'll start checking at tonight

**Comment by martinnnnnnnnnnnnnnnnnnn** [comment]
By the way, glad to see a real dev working on this along with ned. And the work definitely shows. ;)

**Comment by lotsa-spaghetti** [comment]
@d3m3vilurr Script seems to generate good values for o3DS NFIRM, but the freeze still occours. I think the problem maybe is that the random stub might not be dividable by 3 in all versions?

**Comment by nedwill** [comment]
The freeze occurs because the value is not always set correctly. The scheduler is more complicated than I showed at C3 since I didn't have enough time. I believe I can workaround it to near 100% reliability.

**Comment by lotsa-spaghetti** [comment]
On o3DS it never worked, even with the values the script generated for o3DS. I wonder if that's just bad luck or if there needs to be another change.

**Comment by AzizBlooper** [comment]
@kim-yannick so...o3ds just a waste console ever?:'( its very sad news...I just give up about this...I wonder if I just update to latest

**Comment by d3m3vilurr** [comment]
@kim-yannick @AzizBlooper `not always set correctly` mean, if we use wrong `timeout` value, it will never set correctly.
so we need more time for find right timing value.

for example if use `0xaaa5e774` it will always set `0xfff1b65c` in n3ds (but actually not always, but most times)

but i guess it can be still remain timing issue. for example, my code will use `0xaaa5e659` in o3ds 11.2, but it can not fit `0xfff1b30c`. it probably set `0xfff1b30b`. (but if use `0xaaa5e65a`, it will set `0xfff1b30e`)
(this is just my thought, not checked in real device.)
so maybe we'll fix timer.c for this.

**Comment by lotsa-spaghetti** [comment]
@d3m3vilurr That's exactly my thought. It isn't dividable by 3 and loses 1 byte, which might cause the crash. I wonder if there is another way like putting the error inside the start value. That would work I think.

**Comment by ghost** [comment]
Here is an exception dump of the crash:
(11.2 old3ds)
https://gist.github.com/idgrepthat/8cae10cb4f4a34d6df3d2b8362a536c4

(10.7 old3ds)
https://gist.github.com/idgrepthat/e3b71dbc09cb67ab6b8e1d079080ccec

**Comment by lotsa-spaghetti** [comment]
Got it working on o3DS by implementing a simple error correction

**Comment by Earned** [comment]
@kim-yannick Nice ! In which version ?

**Comment by blackwing182** [comment]
@kim-yannick can you share your build for test?

**Comment by lotsa-spaghetti** [comment]
I'm cleaning up the source and will then create a PR. Currently I just added the 11.2 constants.

**Comment by lotsa-spaghetti** [comment]
@d3m3vilurr I made a [PR](https://github.com/d3m3vilurr/fasthax/pull/1) adding an o3DS version table and correcting the division error

If you merge you should change the title of your own PR, because it's now more than N3DS.

**Comment by nedwill** [comment]
I finally got a EUR power adapter (lol) so I have a chance today to do a little work on this. Merging since it looks good and is consistent with the existing style.

**Comment by lotsa-spaghetti** [comment]
@nedwill You merged before @d3m3vilurr merged my PR

**Comment by nedwill** [comment]
I saw that. Do you mind opening a PR here?

**Comment by lotsa-spaghetti** [comment]
I'm doing it rn

**Comment by nedwill** [comment]
BTW, tested on my USA N3DS 11.2 and the new changes work still. Gonna do the cleanups now.

**Pull request merged**
