### PR TITLE
Add dynamic memory search

### PR DESCRIPTION
**Pull request by d3m3vilurr**
this changes can break 11.2 support.(not yet tested)
in my test(on 11.0), now looks like right address.
but still crash on `finalize_global_backdoor`

### CODE REVIEW

**Comment by lotsa-spaghetti** [comment]
Still freezes on o3DS 11.2E, but I think nothing changed for that.

**Comment by kurocygnus** [comment]
I used this fork: https://github.com/noahc3/fasthax and got to the "[+] UAF succeeded and local backdoor installed." message but then it freeze.

**Comment by d3m3vilurr** [comment]
@kim-yannick ah.. really? well i was thought before python script getting wrong address....hm...

**Comment by lotsa-spaghetti** [comment]
@d3m3vilurr https://github.com/nedwill/fasthax/issues/26#issuecomment-270127532

I found that out earlier. It does not even get to cleaning it up.

**Comment by SG3xHERO** [comment]
how do i install fasthax i am running 11.20 35e new 3ds and i put the files in my 3ds folder in sd but it just shows up as a folder

**Comment by d3m3vilurr** [comment]
ok, close this pr, and i'll check @kim-yannick 's comment.

**Comment by lotsa-spaghetti** [comment]
@d3m3vilurr Don't close it, your PR changed nothing to my problem, maybe it is still useful for other versions.

**Comment by lotsa-spaghetti** [comment]
@nedwill should review it

**Comment by d3m3vilurr** [comment]
maybe script will calcurate right position, we don't need dyna memsearch

**Comment by lotsa-spaghetti** [comment]
Okay

**Comment by lotsa-spaghetti** [comment]
@d3m3vilurr You could try finding what the issue for that crash/freeze is, I don't have CFW to debug. Like I said, it seems to happen at the check if the global backdoor still works (https://github.com/nedwill/fasthax/blob/master/source/backdoor.c#L228)

**Pull request closed without merging**
